apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: {{ .Values.mongoExpress.replicaCount }}
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: {{ .Values.mongodb.rootUser | quote }}
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: {{ .Values.mongodb.rootPassword | quote }}
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongodb-service"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: {{ .Values.mongoExpress.nodePort }}
  selector:
    app: mongo-express
